<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="block discount" id="block-discount" data-mage-init='{"collapsible":{"openedState": "active", "saveState": false}}'>
    <div class="title" data-role="title">
        <strong id="block-discount-heading" role="heading" aria-level="2"><?= /* @escapeNotVerified */ __('Apply Discount Code') ?></strong>
    </div>
    <div class="content" data-role="content" aria-labelledby="block-discount-heading">
        <form id="discount-coupon-form"
              action="<?= /* @escapeNotVerified */ $block->getUrl('multicoupon/multi/couponPost') ?>"
              method="post"
              data-mage-init='{"discountCode1":{"couponCodeSelector": "#coupon_code",
                                               "removeCouponSelector": "#remove-coupon",
                                               "inputCouponSelector": "#remove_coupon",
                                               "applyButton": "button.action.apply",
                                               "cancelButton": "a.action.cancel"}}'>
            <div class="fieldset coupon<?= strlen($block->getCouponCode()) ? ' applied' : '' ?>">
                <input type="hidden" name="remove" id="remove-coupon" value="0" />
                <div class="field">
                    <label for="coupon_code" class="label"><span><?= /* @escapeNotVerified */ __('Enter discount code') ?></span></label>
                    <div class="control">
                        <input type="text" class="input-text" id="coupon_code" name="coupon_code" placeholder="<?= $block->escapeHtml(__('Enter discount code')) ?>" />
                    </div>
                </div>
                <div class="actions-toolbar">

                    <div class="primary">
                        <button class="action apply primary" type="button" value="<?= /* @escapeNotVerified */ __('Apply Discount') ?>">
                            <span><?= /* @escapeNotVerified */ __('Apply Discount') ?></span>
                        </button>
                    </div>
                </div>

            </div>
            <?php if (strlen($block->getCouponCode())): ?>
                <h5>Apply Coupon code:</h5>
                <input type="hidden" name="remove_coupon" id="remove_coupon" value="" />
                <?php
                    $array_coupon = explode(',',$block->getCouponCode());
                    foreach ($array_coupon as $coupon):
                ?>
                        <div style="width:100%;margin-bottom: 10px;">
                            <div class="actions-toolbar">
                                <span><?= $coupon ?></span>
                                <a href="#" class="action cancel">Remove</a>
                            </div>
                        </div>

            <?php endforeach; endif; ?>

        </form>
    </div>
</div>